# Generated by Django 5.2 on 2026-10-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_nearby_location_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(
                fields=['status', 'is_active', 'start_datetime'],
                name='event_active_list_idx',
            ),
        ),
    ]
