# Generated by Django 5.2.8 on 2025-12-15 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_email_verified_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-otp_last_generated']},
        ),
        migrations.RemoveField(
            model_name='otp',
            name='otp_created_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_last_generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
