# Generated by Django 5.2.8 on 2026-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_otp_options_otp_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('user', 'User'), ('host', 'Host'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
